dataset_name_or_paths: ["../../watermarks-validation-donut"] # "./dataset/docvqa" # should be prepared from https://rrc.cvc.uab.es/?ch=17
train_batch_sizes: [1]
val_batch_sizes: [1]
check_val_every_n_epochs: 10
check_val_every_n_epoch: 10
max_steps: -1 # infinite, since max_epochs is specified
result_path: "./result"
seed: 2023
resume_from_checkpoint_path: null # only used for resume_from_checkpoint option in PL
pretrained_model_name_or_path: "naver-clova-ix/donut-base" # loading a pre-trained model (from moldehub or path)
sort_json_key: True
input_size: [1280, 960] #[2560, 1920] # when the input resolution differs from the pre-training setting, some weights will be newly initialized (but the model training would be okay)
max_length: 128 #768
align_long_axis: False
# num_nodes: 8 # memo: donut-base-finetuned-docvqa was trained with 8 nodes
num_nodes: 1
lr: 3e-5
warmup_steps: 10000 #300 # 800/8*30/10, 10%
num_training_samples_per_epoch: 120 #39463 #800
max_epochs: 7 #300 #30
num_workers: 2 # 8
val_check_interval: 1.0
gradient_clip_val: 0.25 #1.0
verbose: True
